spring:
datasource:
url: jdbc:postgresql://localhost:5432/KiiwiPWM
username: rafae
password: 12345
driver-class-name: org.postgresql.Driver

jpa:
hibernate:
ddl-auto: update
show-sql: true
properties:
dialect: org.hibernate.dialect.PostgreSQLDialect
